import { useEffect, useState } from 'react';
import { BookOpen, Check, FolderOpen, Save } from 'lucide-react';

export default function ProjectHub({ project, onLoad }: { project: unknown; onLoad: (project: unknown) => void }) {
  const [status, setStatus] = useState('Saved'); const [showGuide, setShowGuide] = useState(false); const [slot, setSlot] = useState('Island Session');
  useEffect(() => { const timer = window.setTimeout(() => { localStorage.setItem('qamelot-project', JSON.stringify(project)); setStatus(`Autosaved ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`); }, 700); return () => window.clearTimeout(timer); }, [project]);
  const saveSlot = () => { const name = window.prompt('Project slot name', slot)?.trim(); if (!name) return; localStorage.setItem(`qamelot-slot-${name}`, JSON.stringify(project)); setSlot(name); setStatus(`Saved “${name}”`); };
  const loadSlot = () => { const name = window.prompt('Load project slot name', slot)?.trim(); if (!name) return; const saved = localStorage.getItem(`qamelot-slot-${name}`); if (saved) { onLoad(JSON.parse(saved)); setSlot(name); setStatus(`Loaded “${name}”`); } else setStatus('Slot not found'); };
  return <div className="flex items-center gap-2 text-xs"><span className="hidden lg:flex items-center gap-1 text-emerald-300"><Check className="w-3 h-3" />{status}</span><button onClick={saveSlot} className="p-2 rounded bg-zinc-800 text-zinc-300" title="Save named project slot"><Save className="w-4 h-4" /></button><button onClick={loadSlot} className="p-2 rounded bg-zinc-800 text-zinc-300" title="Load named project slot"><FolderOpen className="w-4 h-4" /></button><button onClick={() => setShowGuide(true)} className="p-2 rounded bg-zinc-800 text-zinc-300" title="Guided tutorial"><BookOpen className="w-4 h-4" /></button>{showGuide && <div className="fixed inset-0 z-[200] bg-black/70 flex items-center justify-center p-4" onClick={() => setShowGuide(false)}><div className="max-w-md rounded-2xl bg-zinc-950 border border-zinc-700 p-6 space-y-3" onClick={e => e.stopPropagation()}><h3 className="font-bold text-zinc-100">Qamelot Quick Start</h3><ol className="list-decimal pl-5 space-y-2 text-sm text-zinc-300"><li>Press Play to start the island beat.</li><li>Edit steps or use Sequencer Pro for scenes and patterns.</li><li>Use pads and piano to perform or record riffs.</li><li>Shape sounds in Sound Design Lab and mix in the console.</li><li>Save a named slot before experimenting.</li></ol><button onClick={() => setShowGuide(false)} className="w-full rounded bg-cyan-500 py-2 font-bold text-white">Got it</button></div></div>}</div>;
}