import { useEffect, useState } from 'react';
import { AudioLines, Upload } from 'lucide-react';
import { audioEngine } from '../audio/AudioEngine';

type Design = { attack: number; decay: number; sustain: number; release: number; waveform: OscillatorType | 'preset'; unison: number; detune: number; filterEnv: number; glide: number; drive: number; modulation: 'none' | 'chorus' | 'phaser' | 'flanger'; modulationDepth: number; width: number; pump: number };
const STORAGE_KEY = 'qamelot-sound-design';
const DEFAULTS: Design = { attack: 10, decay: 45, sustain: 65, release: 35, waveform: 'preset', unison: 1, detune: 0, filterEnv: 35, glide: 0, drive: 0, modulation: 'none', modulationDepth: 0, width: 0, pump: 0 };

export default function SoundDesignLab() {
  const [design, setDesign] = useState<Design>(() => { try { return { ...DEFAULTS, ...JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}') }; } catch { return DEFAULTS; } });
  const [sampleName, setSampleName] = useState<string | null>(null);
  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify(design)); audioEngine.setSoundDesign(design); }, [design]);
  const update = <K extends keyof Design>(key: K, value: Design[K]) => setDesign(current => ({ ...current, [key]: value }));
  const range = (key: keyof Design, label: string, min: number, max: number) => <label className="text-[10px] text-zinc-500">{label}: {design[key] as number}<input type="range" min={min} max={max} value={design[key] as number} onChange={e => update(key, Number(e.target.value) as never)} className="w-full accent-fuchsia-500" /></label>;
  const importSample = async (file: File | undefined) => { if (!file) return; try { await audioEngine.importSample(file.name, file); setSampleName(file.name); } catch { setSampleName('Import failed'); } };
  return <div className="bg-zinc-950/60 backdrop-blur-xl border border-zinc-800/50 rounded-2xl p-5 shadow-2xl space-y-4"><div className="flex items-center gap-2"><AudioLines className="w-5 h-5 text-fuchsia-400" /><div><h3 className="font-semibold text-zinc-200">Sound Design Lab</h3><p className="text-[10px] text-zinc-500 uppercase">Voice · inserts · samples</p></div></div><div className="grid grid-cols-2 gap-2">{range('attack','Attack',0,120)}{range('decay','Decay',0,100)}{range('sustain','Sustain',0,100)}{range('release','Release',0,150)}{range('filterEnv','Filter Env',0,100)}{range('glide','Glide',0,100)}{range('unison','Unison',1,4)}{range('detune','Detune',0,40)}</div><div className="grid grid-cols-2 gap-2"><label className="text-[10px] text-zinc-500">Waveform<select value={design.waveform} onChange={e => update('waveform', e.target.value as Design['waveform'])} className="mt-1 w-full bg-zinc-800 rounded p-1.5 text-zinc-100"><option value="preset">Preset</option><option value="sine">Sine</option><option value="triangle">Triangle</option><option value="sawtooth">Saw</option><option value="square">Square</option></select></label><label className="text-[10px] text-zinc-500">Modulation<select value={design.modulation} onChange={e => update('modulation', e.target.value as Design['modulation'])} className="mt-1 w-full bg-zinc-800 rounded p-1.5 text-zinc-100"><option value="none">None</option><option value="chorus">Chorus</option><option value="phaser">Phaser</option><option value="flanger">Flanger</option></select></label></div><div className="grid grid-cols-2 gap-2">{range('drive','Drive',0,100)}{range('modulationDepth','Mod Depth',0,100)}{range('width','Stereo Width',0,100)}{range('pump','Sidechain Pump',0,100)}</div><label className="flex items-center justify-center gap-2 cursor-pointer rounded border border-dashed border-zinc-700 p-2 text-xs text-zinc-400 hover:text-cyan-300"><Upload className="w-4 h-4" /> Import one-shot<input type="file" accept="audio/*" onChange={e => importSample(e.target.files?.[0])} className="hidden" /></label>{sampleName && <button onClick={() => audioEngine.playImportedSample(sampleName)} className="w-full rounded bg-cyan-500/15 border border-cyan-500/30 py-2 text-xs font-bold text-cyan-200">Play imported: {sampleName}</button>}</div>;
}